name: ml_dsa
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/jasoncolburne/ml-dsa-dart

environment:
  sdk: ^3.6.0

dependencies:
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^5.0.0
  hex: ^0.2.0
  test: ^1.24.0
