name: Dart Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart --enable-experiment=native-assets run build.dart
      - run: dart --enable-experiment=native-assets run test/ml_dsa_test.dart

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart --enable-experiment=native-assets run build.dart
      - run: dart --enable-experiment=native-assets compile exe test/ml_dsa_benchmark_test.dart -o benchmarks
      - run: ./benchmarks

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart format lib -o none --set-exit-if-changed
